package com.dam1.unidad1

fun mostrarMenu(){
    println("**Menu**")
    println("**1: Ejercicio_1**")
    println("**2: Ejercicio_2**")
    println("**3: Ejercicio_3**")
    println("**4: Ejercicio_4**")
    println("**5: Ejercicio_5**")
    println("**6: Ejercicio_6**")
    println("**7: Ejercicio_7**")
    println("**8: Ejercicio_8**")
    println("**9: Ejercicio_9**")
    println("**10: Ejercicio_10**")
    println("**11: Ejercicio_11**")
    println("**12: Ejercicio_12**")
    println("**13: Ejercicio_13**")
    println("**14: Ejercicio_14**")
    println("**15: Ejercicio_15**")
    println("**16: Ejercicio_16**")
    println("**17: Ejercicio_17**")
    println("**18: Ejercicio_18**")
    println("**19: Ejercicio_19**")
    println("**20: Ejercicio_20**")
    println("**21: Ejercicio_21**")
}